print('')
print('BMI計算機')
print('')
性別=input('1.請輸入性別(男/女)：')
print('')
身高= input('2.請輸入身高(cm)： ')
print('')
體重=input('3.請輸入體重(kg)： ')
print('')
print('')
print('<<<計算結果>>>')
print('')
print('您的性別是：', 性別)
print('')
print('這是您的身高及體重：', 身高,'cm','、', 體重,'kg')
print('')
身高= int(身高)
x= 身高/100
體重=int(體重)
BMI= 體重/(x*2)   
print('這是您的BMI值：', BMI)
print('')
print('<<<計算結束>>>')
print('')